wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1652007780
    t:
      1:
      - 1
      - 41
      - 43
      2:
      - 1
      - 41
      - 43
      3:
      - 35
      4: 3.9.10
      5: 0.12.11
      8:
      - 3
      - 5
